# Generated by Django 2.2.16 on 2022-07-31 10:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flower', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentToItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Введите текст комментария', verbose_name='Текст комментария')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_to_item', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_to_item', to='flower.Item', verbose_name='товар')),
            ],
            options={
                'verbose_name': 'Комментарий к товару',
                'verbose_name_plural': 'Комментарии к товару',
            },
        ),
        migrations.CreateModel(
            name='CommentToSeller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Введите текст комментария', verbose_name='Текст комментария')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_to_seller', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='Продавец')),
            ],
            options={
                'verbose_name': 'Комментарий к продавцу',
                'verbose_name_plural': 'Комментарии к продавцу',
            },
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
