# Generated by Django 2.2.16 on 2022-07-31 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flower', '0002_auto_20220731_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commenttoitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='flower.Item', verbose_name='товар'),
        ),
    ]
