# Generated by Django 2.2.16 on 2022-07-31 10:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flower', '0004_auto_20220731_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='deals', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='deal',
            name='lot',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='flower.Item', verbose_name='Автор'),
            preserve_default=False,
        ),
    ]
